<?php
/**
 * MyBB 1.8 Romanian Language Pack
 * Copyright 2014 MyBB Romania, Toate drepturile rezervate.
 *
 */
$l['post_thread'] = "Posteaz&#259; Subiect";
$l['moderated_by'] = "Moderat De:";
$l['nothreads'] = "Ne pare r&#259;u, dar acum nu sunt subiecte &#238;n acest forum cu limitele de dat&#259; &#351;i timp specificate.";
$l['nopermission'] = "Ne pare r&#259;u, dar nu ave&#355;i permisiunea necesar&#259; pentru a vedea subiectele din acest forum.";
$l['search_forum'] = "Caut&#259; &#238;n acest Forum:";
$l['thread'] = "Subiect";
$l['author'] = "Autor";
$l['replies'] = "R&#259;spunsuri";
$l['views'] = "Vizualiz&#259;ri";
$l['lastpost'] = "Ultimul Mesaj";
$l['rating'] = "Rating";
$l['prefix'] = "Prefix:";
$l['prefix_all'] = "Prefix: Toate/Niciun Prefixele";
$l['prefix_any'] = "Prefix: Toate Prefixele";
$l['prefix_none'] = "Prefix: Niciun Prefix";
$l['markforum_read'] = "Marcheaz&#259; acest forum ca citit";
$l['subscribe_forum'] = "Aboneaz&#259;-te la acest forum";
$l['unsubscribe_forum'] = "Dezabona&#355;i-v&#259; de la acest forum";
$l['clear_stored_password'] = "&#350;terge parola salvat&#259; pentru forum";
$l['sort_by_subject'] = "Sorteaz&#259; dup&#259;: Subiect";
$l['sort_by_lastpost'] = "Sorteaz&#259; dup&#259;: Ultimul Mesaj";
$l['sort_by_starter'] = "Sorteaz&#259; dup&#259;: Autor";
$l['sort_by_started'] = "Sorteaz&#259; dup&#259;: Timpul de Creare";
$l['sort_by_rating'] = "Sorteaz&#259; dup&#259;: Rating";
$l['sort_by_replies'] = "Sorteaz&#259; dup&#259;: R&#259;spunsuri";
$l['sort_by_views'] = "Sorteaz&#259; dup&#259;: Vizualiz&#259;ri";
$l['sort_order_asc'] = "Ordoneaz&#259;: Cresc&#259;tor";
$l['sort_order_desc'] = "Ordoneaz&#259;: Descresc&#259;tor";
$l['datelimit_1day'] = "De: Ast&#259;zi";
$l['datelimit_5days'] = "De: Acum 5 Zile";
$l['datelimit_10days'] = "De: Acum 10 Zile";
$l['datelimit_20days'] = "De: Acum 20 Zile";
$l['datelimit_50days'] = "De: Acum 50 Zile";
$l['datelimit_75days'] = "De: Acum 75 Zile";
$l['datelimit_100days'] = "De: Acum 100 Zile";
$l['datelimit_lastyear'] = "De: Anul Trecut";
$l['datelimit_beginning'] = "De: La &#206;nceput";
$l['new_thread'] = "Mesaje Noi";
$l['new_hot_thread'] = "Subiect Fierbinte (Nou)";
$l['posts_by_you'] = "Con&#355;ine Mesaje de-ale Tale";
$l['no_new_thread'] = "F&#259;r&#259; Mesaje Noi";
$l['hot_thread'] = "Subiect Fierbinte (Vechi)";
$l['locked_thread'] = "Subiect &#206;nchis";
$l['goto_first_unread'] = "Du-te la primul mesaj necitit";
$l['pages'] = "Pagini:";
$l['pages_last'] = "ultima";
$l['users_browsing_forum'] = "Utilizator(i) care navigheaz&#259; acest forum:";
$l['users_browsing_forum_guests'] = "{1} Musafir(i)";
$l['users_browsing_forum_invis'] = "{1} Utilizator (i) invizibil (i)";
$l['delayed_moderation'] = "Moderare &#238;nt&#226;rziat&#259;";
$l['inline_thread_moderation'] = "Moderare &#238;n interiorul subiectelor:";
$l['close_threads'] = "&#206;nchide Subiecte";
$l['open_threads'] = "Deschide Subiecte";
$l['stick_threads'] = "Lipe&#351;te Subiecte";
$l['unstick_threads'] = "Dezlipe&#351;te Subiecte";
$l['soft_delete_threads'] = "&#350;terge Subiecte Temporar";
$l['restore_threads'] = "Recupereaz&#259; subiecte";
$l['delete_threads'] = "&#350;terge Subiecte Permanent";
$l['move_threads'] = "Mut&#259; Subiecte";
$l['approve_threads'] = "Aprob&#259; Subiecte";
$l['unapprove_threads'] = "Dezaprob&#259; Subiecte";
$l['inline_go'] = "Du-te";
$l['clear'] = "&#350;terge";
$l['sub_forums_in']  = "Forumuri &#238;n '{1}'";
$l['forum_rules'] = "{1} - Reguli";
$l['subforums'] = "<strong>Subforumuri:</strong>";
$l['asc'] = "cres";
$l['desc'] = "descresc";
$l['forum_announcements'] = "Anun&#355;uri Forum";
$l['sticky_threads'] = "Subiecte Importante";
$l['normal_threads'] = "Subiecte Normale";
$l['icon_dot'] = "Con&#355;ine mesaje de-ale tale. "; // The spaces for the icon labels are strategically placed so that there should be no extra space at the beginning or end of the resulting label and that spaces separate each 'status' ;)
$l['icon_no_new'] = "F&#259;r&#259; mesaje noi.";
$l['icon_new'] = "Mesaje noi.";
$l['icon_hot'] = " Mesaj fierbinte.";
$l['icon_lock'] = " Mesaj &#238;nchis.";
$l['attachment_count'] = "Acest subiect con&#355;ine un ata&#351;ament.";
$l['attachment_count_multiple'] = "Acest subiect con&#355;ine {1} ata&#351;amente.";
$l['rss_discovery_forum'] = "Ultimele Subiecte &#238;n {1}";
$l['forum_unapproved_posts_count'] = "Acum sunt {1} mesaje neaprobate &#238;n acest forum.";
$l['forum_unapproved_post_count'] = "Acum este un mesaj neaprobat &#238;n acest forum.";
$l['forum_unapproved_threads_count'] = "Acum sunt {1} subiecte neaprobate &#238;n acest forum.";
$l['forum_unapproved_thread_count'] = "Acum sunt un subiect neaprobat &#238;n acest forum.";
$l['thread_unapproved_posts_count'] = "Acum sunt {1} mesaje neaprobate &#238;n acest subiect.";
$l['thread_unapproved_post_count'] = "Acum este un mesaj neaprobat &#238;n acest subiect.";
$l['page_selected'] = "Toate <strong>{1}</strong> subiectele din aceast&#259; pagin&#259; sunt selectate.";
$l['all_selected'] = "Toate <strong>{1}</strong> subiectele din acest forum sunt selectate.";
$l['select_all'] = "Selecteaz&#259; toate <strong>{1}</strong> subiectele din acest forum.";
$l['clear_selection'] = "Deselecteaz&#259;.";
$l['error_containsnoforums'] = "Ne pare r&#259;u dar forumul pe care &#238;l vizitezi acum nu con&#355;ine niciun subforum.";
$l['inline_edit_description'] = '(Apasă şi ţine apăsat clic pentru a edita)';