<?php
/**
 * MyBB 1.8 Romanian Language Pack
 * Copyright 2014 MyBB Romania, Toate drepturile rezervate.
 *
 */

$l['nav_online'] = "Cine este conectat";
$l['nav_onlinetoday'] = "Cine a fost conectat ast&#259;zi";

$l['viewing_announcements'] = "Vizualizare anun&#355; <a href=\"{1}\">{2}</a>";
$l['viewing_announcements2'] = "Vizualizare anun&#355;";
$l['viewing_attachment'] = "Vizualizare ata&#351;ament";
$l['viewing_attachment2'] = "Vizualizare <a href=\"attachment.php?aid={1}\" target=\"_blank\">ata&#351;ament</a> &#238;n subiect <a href=\"{3}\">{2}</a>";
$l['viewing_calendar'] = "Vizualizare <a href=\"calendar.php\">Calendar</a>";
$l['viewing_event'] = "Vizualizare eveniment";
$l['viewing_event2'] = "Vizualizare eveniment <a href=\"{1}\">{2}</a>";
$l['adding_event'] = "<a href=\"calendar.php?action=addevent\">Ad&#259;ugare eveniment</a>";
$l['editing_event'] = "Editare eveniment";
$l['viewing_contact_us'] = "Vizualiz&#226;nd <a href=\"contact.php\">Contacteaz&#259;-ne</a>";
$l['editing_post'] = "Editare mesaj";
$l['viewing_forum'] = "Vizualizare forum";
$l['viewing_forum2'] = "Vizualizare forum <a href=\"{1}\">{2}</a>";
$l['forum_redirect_to'] = "Redirectare c&#259;tre <a href=\"{1}\">{2}</a>";
$l['viewing_index'] = "{1} <a href=\"index.php\">Pagina principal&#259;</a>";
$l['activating_account'] = "Activare cont";
$l['viewing_profile'] = "Vizualizare profil";
$l['viewing_profile2'] = "Vizualizare profil pentru <a href=\"{1}\">{2}</a>";
$l['registering'] = "<a href=\"member.php?action=register\">&#206;nregistrare</a>";
$l['logging_in'] = "<a href=\"member.php?action=login\">Autentificare</a>";
$l['logging_in_plain'] = "Logare";
$l['logging_out'] = "Delogare";
$l['emailing_user'] = "Trimitere email c&#259;tre un utilizator";
$l['rating_user'] = "Evaluare utilizator";
$l['viewing_memberlist'] = "Vizualizare <a href=\"memberlist.php\">list&#259; de membri</a>";
$l['viewing_whoposted'] = "Vizualiz&#226;nd cine a postat";
$l['viewing_whoposted2'] = "Vizualiz&#226;nd cine a postat &#238;n subiectul <a href=\"{1}\">{2}</a>";
$l['marking_read'] = "<a href=\"misc.php?action=markread&#38;my_post_key={1}\">Marcheaz&#259; forumurile ca fiind citite</a>";
$l['viewing_helpdocs'] = "Vizualiz&#226;nd <a href=\"misc.php?action=help\">documente ajutor</a>";
$l['viewing_buddylist'] = "Vizualiz&#226;nd <a href=\"misc.php?action=buddypopup\">list&#259; de prieteni</a>";
$l['viewing_smilies'] = "Vizualiz&#226;nd <a href=\"misc.php?action=smilies\">list&#259; de z&#226;mbete</a>";
$l['viewing_syndication'] = "Vizualiz&#226;nd pagina de <a href=\"misc.php?action=syndication\">RSS Syndication</a>";
$l['replying_thread'] = "R&#259;spunz&#226;nd la subiect";
$l['replying_thread2'] = "R&#259;spunz&#226;nd la subiectul <a href=\"{1}\">{2}</a>";
$l['posting_thread'] = "Post&#226;nd subiect nou";
$l['posting_thread2'] = "Post&#226;nd subiect nou &#238;n <a href=\"{1}\">{2}</a>";
$l['viewing_wol'] = "Vizualiz&#226;nd <a href=\"online.php\">Cine este conectat</a>";
$l['viewing_woltoday'] = "Vizualiz&#226;nd <a href=\"online.php?action=today\">Cine a fost conectat ast&#259;zi</a>";
$l['creating_poll'] = "Cre&#226;nd sondaj nou";
$l['editing_poll'] = "Editare sondaj";
$l['viewing_pollresults'] = "Vizualizare rezultate sondaj";
$l['voting_poll'] = "Votare &#238;n sondaj";
$l['using_modtools'] = "Folosire unelte moderator";
$l['sending_pm'] = "Trimitere mesaj privat";
$l['reading_pm'] = "Citire mesaj privat";
$l['editing_pmfolders'] = "Editare directoare MP";
$l['using_pmsystem'] = "Folosire sistem MP";
$l['reporting_post'] = "Raportare mesaj";
$l['searching_forum'] = "<a href=\"search.php\">C&#259;utare</a> {1}";
$l['reading_thread'] = "Citire subiect";
$l['reading_thread2'] = "Citind subiectul <a href=\"{1}\">{2}</a> {3}";
$l['viewing_team'] = "Vizualiz&#226;nd echipa forumului";
$l['viewing_stats'] = "Vizualiz&#226;nd statisticile forumului";
$l['updating_profile'] = "<a href=\"usercp.php?action=profile\">Actualiz&#226;nd profilul</a>";
$l['updating_options'] = "<a href=\"usercp.php?action=options\">Actualiz&#226;nd op&#355;iuni</a>";
$l['editing_signature'] = "<a href=\"usercp.php?action=editsig\">Edit&#226;nd semn&#259;tura</a>";
$l['changing_avatar'] = "<a href=\"usercp.php?action=avatar\">Schimb&#226;nd avatarul</a>";
$l['viewing_subscriptions'] = "Vizualizand <a href=\"usercp.php?action=subscriptions\">subscriere la subiecte</a>";
$l['editing_pad'] = "Editand <a href=\"usercp.php?action=notepad\">Carne&#355;el personal</a>";
$l['editing_password'] = "Editeaza <a href=\"usercp.php?action=password\">parol&#259;</a>";
$l['user_cp'] = "Vizualizand <a href=\"usercp.php\">panoul de comand&#259; al utilizatorului</a>";
$l['viewing_portal'] = "Vizualiz&#226;nd pagina de <a href=\"portal.php\">Portal</a>";
$l['viewing_noperms'] = "Vizualiz&#226;nd pagina f&#259;r&#259; permisiuni";
$l['unknown_location'] = "<a href=\"{1}\">Loca&#355;ie necunoscut&#259;</a>";
$l['giving_reputation'] = "D&#226;nd o reputa&#355;ie lui <a href=\"{1}\">{2}</a>";
$l['viewing_reputation_report'] = "Vizualiz&#226;nd reputa&#355;ia lui <a href=\"{1}\">{2}</a>";
$l['viewing_reputation_report2'] = "Vizualiz&#226;nd reputa&#355;ia";
$l['member_resendactivation'] = "Retrimi&#355;&#226;nd email pentru activare cont";
$l['member_lostpw'] = "Recuper&#226;nd <a href=\"member.php?action=lostpw\">parol&#259; pierdut&#259;</a>";
$l['sending_thread'] = "Trimi&#355;&#226;nd un subiect unui prieten";

$l['page'] = "Pagin&#259;";
$l['users_online'] = "Cine este conectat";
$l['on_username'] = "Nume utilizator";
$l['time'] = "Or&#259;";
$l['location'] = "Loca&#355;ie";
$l['online_today'] = "Cine a fost conectat ast&#259;zi";
$l['refresh_page'] = "Re&#238;mprosp&#259;teaz&#259; aceast&#259; pagin&#259;";
$l['online_online_plural'] = "utilizatori";
$l['online_online_singular'] = "utilizator";
$l['online_member_plural'] = "membri";
$l['online_member_singular'] = "membru";
$l['online_anon_plural'] = "sunt";
$l['online_anon_singular'] = "este";
$l['online_guest_plural'] = "musafiri";
$l['online_guest_singular'] = "musafir";
$l['online_count'] = "{1} {2} activi &#238;n ultimele {3} minute ({4} {5}, {6} din care {7} invizibili &#351;i {8} {9}).";
$l['ip'] = "IP:";
$l['resolves_to'] = "Nume Gazd&#259;:";
$l['if_resolvable'] = "(dac&#259; este rezolvabil&#259;)";
$l['admin_options'] = "Op&#355;iuni admin:";
$l['search_regip_users'] = "Caut&#259; membri care s-au &#238;nregistrat cu acest IP";
$l['search_postip_users'] = "Caut&#259; membri care au postat utiliz&#226;nd acest IP";
$l['lookup'] = "[c&#259;utare]";
$l['member_online_today'] = "<strong>1</strong> membru a fost conectat ast&#259;zi";
$l['members_were_online_today'] = "<strong>{1}</strong> membri au fost conecta&#355;i ast&#259;zi";
$l['member_online_hidden'] = " ({1} membru a fost invizibil)";
$l['members_online_hidden'] = " ({1} membri au fost invizibili)";
$l['rating_thread'] = "Evaluare Subiect";
$l['viewing_imcenter'] = "Vizualiz&#226;nd centru IM";
$l['managing_favorites'] = "Lucr&#226;nd cu subiecte favorite";
$l['managing_subscriptions'] = "Lucr&#226;nd cu subiecte subscrise";
$l['managing_group'] = "Lucr&#226;nd cu un Grup de utilizatori";
$l['viewing_modcp'] = "Vizualiz&#226;nd PC Moderator";
$l['viewing_modlogs'] = "Vizualiz&#226;nd Log-uri Moderator";
$l['managing_announcements'] = "Lucr&#226;nd cu anun&#355;uri";
$l['search_for_user'] = "C&#259;ut&#226;nd utilizatori";
$l['managing_warninglogs'] = "Administr&#226;nd log-uri de aten&#355;ionare";
$l['searching_ips'] = "C&#259;ut&#226;nd IP-uri";
$l['viewing_reports'] = "Vizualiz&#226;nd mesaje raportate";
$l['adding_announcement'] = "Ad&#259;ug&#226;nd un anun&#355;";
$l['deleting_announcement'] = "&#350;terg&#226;nd un anun&#355;";
$l['editing_announcement'] = "Edit&#226;nd un anun&#355;";
$l['managing_modqueue'] = "Administr&#226;nd coada de moderare";
$l['editing_user_profiles'] = "Edit&#226;nd profil utilizator";
$l['managing_bans'] = "Administr&#226;nd Banuri";
$l['revoking_warning'] = "Revoc&#226;nd o avertizare";
$l['warning_user'] = "Aten&#355;ion&#226;nd un utilizator";
$l['viewing_warning'] = "Vizualiz&#226;nd o avertizare";
$l['managing_warnings'] = "Administr&#226;nd avertiz&#259;ri";
$l['changing_dst'] = "Schimbare comutator ora var&#259;";
$l['printing_thread'] = "Tip&#259;rind un subiect";
$l['printing_thread2'] = "Tip&#259;rind subiectul <a href=\"{1}\">{2}</a>";
$l['managing_buddyignorelist'] = "Administr&#226;nd list&#259; prieteni/Ignore";
